version: '3.7'
services:
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:3.3.1
    ports:
      - "8080:8080"
  vpd06:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ARCHITECTURE_TYPE=CMA
      - ATE_TIER=ct
      - BACKEND_HOST=wiremock
      - BACKEND_PORT=8080
      - BACKEND_PATH=RESTAdapter/generic/approval-status
    ports:
      - "8085:8080"
      - "8888:8888"